on:
  push:
    branches:
      - master

env:
  Version: 1.0.0
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
    - uses: actions/setup-dotnet@51f68377c181a79065c61bd492bd49be4575c439 # pin@v1
    - run: dotnet build -c Release
    - run: dotnet publish -c Release FolderSync/FolderSync.csproj -o release/FolderSync /p:Version=${{ env.Version }}
    - uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # pin@v1
      with:
        name: FolderSync
        path: release/FolderSync
